syntax = "proto3";

package patchbukkit.world;

import "patchbukkit/common/types.proto";

option java_multiple_files = true;
option java_package = "patchbukkit.world";

message GetBlockDataRequest {
  patchbukkit.common.UUID world_uuid = 1;
  int32 x = 2;
  int32 y = 3;
  int32 z = 4;
}

message GetBlockDataResponse {
  string block_state = 1;
}

message SetBlockDataRequest {
  patchbukkit.common.UUID world_uuid = 1;
  int32 x = 2;
  int32 y = 3;
  int32 z = 4;
  string block_state = 5;
  bool apply_physics = 6;
}

message SpawnParticleRequest {
  patchbukkit.common.UUID world_uuid = 1;
  string particle = 2;
  double x = 3;
  double y = 4;
  double z = 5;
  int32 count = 6;
  double offset_x = 7;
  double offset_y = 8;
  double offset_z = 9;
  double extra = 10;
}

message GetWorldsResponse {
  repeated patchbukkit.common.UUID world_uuids = 1;
}

message WorldBorderData {
  double center_x = 1;
  double center_z = 2;
  double size = 3;
  double target_size = 4;
  int64 speed = 5;
  int32 warning_time = 6;
  int32 warning_blocks = 7;
  double damage_per_block = 8;
  double damage_buffer = 9;
  int32 max_center_coordinate = 10;
}

message GetWorldBorderRequest {
  patchbukkit.common.UUID world_uuid = 1;
}

message SetWorldBorderRequest {
  patchbukkit.common.UUID world_uuid = 1;
  WorldBorderData border = 2;
}

message GetWorldInfoRequest {
  patchbukkit.common.UUID world_uuid = 1;
}

message GetWorldInfoResponse {
  int32 min_height = 1;
  int32 max_height = 2;
  int32 height = 3;
  int64 seed = 4;
}

message GetLoadedChunksRequest {
  patchbukkit.common.UUID world_uuid = 1;
}

message ChunkPosition {
  int32 x = 1;
  int32 z = 2;
}

message GetLoadedChunksResponse {
  repeated ChunkPosition chunks = 1;
}

message IsChunkLoadedRequest {
  patchbukkit.common.UUID world_uuid = 1;
  int32 x = 2;
  int32 z = 3;
}

message IsChunkLoadedResponse {
  bool loaded = 1;
}

