syntax = "proto3";
package patchbukkit.events;

import "patchbukkit/common/types.proto";

option java_multiple_files = true;
option java_package = "patchbukkit.events";

message PlayerJoinEvent {
  patchbukkit.common.UUID player_uuid = 1;
  string join_message = 2;
}

message PlayerQuitEvent {
  patchbukkit.common.UUID player_uuid = 1;
  string quit_message = 2;
}

message PlayerInteractEvent {
  patchbukkit.common.UUID player_uuid = 1;
  string action = 2;
  int32 clicked_x = 3;
  int32 clicked_y = 4;
  int32 clicked_z = 5;
  string block_face = 6;
  string hand = 7;
}

message PlayerGameModeChangeEvent {
  patchbukkit.common.UUID player_uuid = 1;
  string new_gamemode = 2;
}

message PlayerToggleSneakEvent {
  patchbukkit.common.UUID player_uuid = 1;
  bool is_sneaking = 2;
}

message PlayerToggleSprintEvent {
  patchbukkit.common.UUID player_uuid = 1;
  bool is_sprinting = 2;
}

message PlayerToggleFlightEvent {
  patchbukkit.common.UUID player_uuid = 1;
  bool is_flying = 2;
}

message PlayerChatEvent {
  patchbukkit.common.UUID player_uuid = 1;
  string message = 2;
  string format = 3;
}

message PlayerMoveEvent {
  patchbukkit.common.UUID player_uuid = 1;
  patchbukkit.common.Location from = 2;
  patchbukkit.common.Location to = 3;
}

message PlayerInteractEntityEvent {
  patchbukkit.common.UUID player_uuid = 1;
  patchbukkit.common.UUID target_uuid = 2;
  string action = 3;
  bool is_sneaking = 4;
}

message PlayerResourcePackStatusEvent {
  patchbukkit.common.UUID player_uuid = 1;
  patchbukkit.common.UUID pack_uuid = 2;
  string status = 3;
}

